CS-700 Assignment 2: ArraySorting Class Reference
ArraySorting Class Reference
#include <arraySorting.h>
Public Member Functions
ArraySorting (int)
explicit Constructor taking 1 param
void display ()
method taking no param
Private Member Functions
void createRandomIntArray ()
method taking no param
void mergeSortArray (int[], unsigned int, unsigned int)
method taking taking 3 params
void mergeSubArrays (int[], unsigned int &, unsigned int &, unsigned int &)
method taking taking 4 params
void copyNewArrayIntoOriginalArray (const int[], int[], unsigned int, unsigned int)
method taking taking 4 params
void swap (int &, int &)
method taking taking 2 params
void printDoubleDivider ()
method taking no param
void printDivider ()
method taking no param
void printHeader ()
method taking no param
void printRandomTimeResult ()
method taking no param
void printSortedTimeResult ()
method taking no param
void printReverseTimeResult ()
method taking no param
void printArraySize () const
method taking no param
void sortArray (double timeArray[])
method taking no param
void reverseSortedArray ()
method taking no param
Private Attributes
unsigned int SIZE_OF_2D_ARRAY
unsigned int variable declared.
double estimatedTimeForSortingRandomArr [NUMBER_OF_ARRAYS] {}
double array declared
double estimatedTimeForSortingSortedArr [NUMBER_OF_ARRAYS] {}
double array declared
double estimatedTimeForReversingSortedArr [NUMBER_OF_ARRAYS] {}
double array declared
int ** array = new int * [NUMBER_OF_ARRAYS]
2D int ** array. In a two dimensional array, we can access each element by using two subscripts, where first subscript represents the row number and second subscript represents the column number. int ** array point to a int * array which holds a pointer to an int value for each element.
Static Private Attributes
static const int NUMBER_OF_ARRAYS = 10
int variable assigned value 10.
Detailed Description
Code placed here is included only once per translation unit.
'#pragma once' is non-standard preprocessor directive intended for implementing compiler-specific preprocessor instructions.
It's purpose is to replace the include guards that you use in header files to avoid multiple inclusion.
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: Class is a user-defined data type, which holds its own data members and member functions, which can be accessed and used by creating an instance of that class. Defining variables, methods and constructors.
Definition at line 44 of file arraySorting.h.
Constructor & Destructor Documentation
ArraySorting()
ArraySorting::ArraySorting (int size) explicit
explicit Constructor taking 1 param
Parameters
[in] int
Returns
[out] void
Precondition
Pre Condition - an integer is passed
Postcondition
Post Condition - various operations are performed on a array of size N.
variable ArraySorting::SIZE_OF_2D_ARRAY is initialized value passed in the constructor.
The pseudo-random number generator is initialized using the argument passed as seed.
For every different seed value used in a call to srand, the pseudo-random number generator can be expected to generate a different succession of results in the subsequent calls to rand. passed time(0) function that returns the current time in seconds.
createRandomIntArray() function call to create an array with random numbers.
sortArray() function call to sort the array and calculate the execution time for sorting random array.
sortArray() function call to sort the array and calculate the execution time for sorting sorted array.
reverseSortedArray() function call to reverse the array.
sortArray() function call to sort the array and calculate the execution time for sorting reversed array.
Definition at line 26 of file arraySorting.cpp.
{
    SIZE_OF_2D_ARRAY = size;
    srand(time(0));
    createRandomIntArray();
    sortArray(estimatedTimeForSortingRandomArr);
    sortArray(estimatedTimeForSortingSortedArr);
    reverseSortedArray();
    sortArray(estimatedTimeForReversingSortedArr);
}
References createRandomIntArray(), estimatedTimeForReversingSortedArr, estimatedTimeForSortingRandomArr, estimatedTimeForSortingSortedArr, reverseSortedArray(), SIZE_OF_2D_ARRAY, and sortArray().
Member Function Documentation
copyNewArrayIntoOriginalArray()
void ArraySorting::copyNewArrayIntoOriginalArray (const int newArray[], int originalArray[], unsigned int arrayLength, unsigned int index) private
method taking taking 4 params
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: Method to copy the values of an array to another array
Parameters
[in] newArray
[in] originalArray
[in] arrayLength
[in] index
Returns
[out] void
Precondition
Pre Condition - 2 arrays, and 2 unsigned int values are passed
Postcondition
Post Condition - array is copied to another array.
Definition at line 195 of file arraySorting.cpp.
{
    for (int i = 0; i < arrayLength; index++, i++) {
        originalArray[index] = newArray[i];
    }
}
Referenced by mergeSubArrays().
createRandomIntArray()
void ArraySorting::createRandomIntArray () private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: Method to fill the array with random positive integers between 1-SIZE OF 2D ARRAY.
Parameters
[in,out] void
Returns
[out] void
Postcondition
Post Condition - a 2D int pointer array is initialized with random values.
using for loop to iterate through each array U as a suffix to 0 means only unsigned values
creating an array of integers of size ArraySorting::SIZE_OF_2D_ARRAY
U as a suffix to 0 means only unsigned values
using rand() function to generate a random value from 1 to SIZE_OF_2D_ARRAY and assigning to the array
Definition at line 51 of file arraySorting.cpp.
{
    for (int i = 0U; i < NUMBER_OF_ARRAYS; i++) {
        array[i] = new int[SIZE_OF_2D_ARRAY];
        for (int j = 0U; j < SIZE_OF_2D_ARRAY; j++) {
            array[i][j] = rand() % SIZE_OF_2D_ARRAY + 1;
        }
    }
}
References array, NUMBER_OF_ARRAYS, and SIZE_OF_2D_ARRAY.
Referenced by ArraySorting().
display()
void ArraySorting::display ()
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: Method to display a table of execution time of each array for random, sorted and reverse time in a well formatted fashion.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - a table is printed to the console.
calling this function ArraySorting::printArraySize to print the array size taken.
calling this function ArraySorting::printDoubleDivider to print a divider line.
calling this function ArraySorting::printHeader to print the header of the table.
calling this function ArraySorting::printDoubleDivider to print a divider line.
calling this function ArraySorting::printRandomTimeResult to print the random time results for each array.
calling this function ArraySorting::printDivider to print a divider line.
calling this function ArraySorting::printSortedTimeResult to print the sorted time results for each array.
calling this function ArraySorting::printDivider to print a divider line.
calling this function ArraySorting::printReverseTimeResult to print the reverse time results for each array.
calling this function ArraySorting::printDoubleDivider to print a divider line.
Definition at line 279 of file arraySorting.cpp.
{
    printArraySize();
    printDoubleDivider();
    printHeader();
    printDoubleDivider();
    printRandomTimeResult();
    printDivider();
    printSortedTimeResult();
    printDivider();
    printReverseTimeResult();
    printDoubleDivider();
}
References printArraySize(), printDivider(), printDoubleDivider(), printHeader(), printRandomTimeResult(), printReverseTimeResult(), and printSortedTimeResult().
Referenced by arraySortingModule().
mergeSortArray()
void ArraySorting::mergeSortArray (int subArray[], unsigned int leftIndex, unsigned int rightIndex) private
method taking taking 3 params
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: Method to sort array using merge sort algorithm.
The Merge Sort algorithm is a sorting algorithm that is based on the Divide and Conquer paradigm.
Parameters
[in] subArray
[in] leftIndex
[in] rightIndex
Returns
[out] void
Precondition
Pre Condition - an array, and 2 unsigned int values are passed
Postcondition
Post Condition - recursion is used to sort array
if the left index is greater or equal to the right index then return, it means the all elements of array is traversed.
assign value to middleIndex by subtracting leftIndex from rightIndex then dividing by 2 and then adding it to leftIndex.
recursion call to ArraySorting::mergeSortArray takes array, leftIndex, and middleIndex as arguments.
recursion call to ArraySorting::mergeSortArray takes array, middleIndex+1, and rightIndex as arguments.
function ArraySorting::mergeSubArrays called to merge the sorted arrays takes array, leftIndex, middleIndex and rightIndex as arguments.
Definition at line 76 of file arraySorting.cpp.
{
    if (leftIndex >= rightIndex) {
        return;
    }
    unsigned int middleIndex = leftIndex + (rightIndex - leftIndex) / 2;
    mergeSortArray(subArray, leftIndex, middleIndex);
    mergeSortArray(subArray, middleIndex + 1, rightIndex);
    mergeSubArrays(subArray, leftIndex, middleIndex, rightIndex);
}
References mergeSortArray(), and mergeSubArrays().
Referenced by mergeSortArray(), and sortArray().
mergeSubArrays()
void ArraySorting::mergeSubArrays (int subArray[], unsigned int & leftIndex, unsigned int & middleIndex, unsigned int & rightIndex) private
method taking taking 4 params
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: Method to merge the sorted arrays.
Parameters
[in] subArray
[in] leftIndex
[in] middleIndex
[in] rightIndex
Returns
[out] void
Precondition
Pre Condition - an array, and 3 unsigned int values are passed
Initializing an int pointer array.
int * array holds a pointer to an int value for each element.
assigning leftIndex value to an unsigned int startIndexPointer variable.
assigning middleIndex+1 value to an unsigned int endIndexPointer variable.
assigning 0 to newIndexPointer variable.
using while loop to insert value of old array to new array in sorted manner, until startIndexPointer is less than or equal to middleIndex and endIndexPointer is also less than and equal to rightIndex.
if the element at startIndex is less than or equal to the element at endIndex
assign value of old array at startIndex to new array.
increment startIndexPointer
else assigning value of old array at endIndex to new array.
increment endIndexPointer
increment newIndexPointer
using while loop to insert value of old array to new array in sorted manner, until startIndexPointer is less than or equal to middleIndex which indicates the array is not completely inserted to the new array.
assign value of old array at startIndex to new array.
increment startIndexPointer
increment newIndexPointer
using while loop to insert value of old array to new array in sorted manner, until endIndexPointer is less than or equal to rightIndex which indicates the array is not completely inserted to the new array.
assign value of old array at endIndex to new array.
increment endIndexPointer
increment newIndexPointer
function ArraySorting::copyNewArrayIntoOriginalArray is called to copy the values of new array into the old array. takes newSubArray, subArray, rightIndex - leftIndex + 1, and leftIndex as arguments.
deleting the new array after the content of it is copied to the old array. freeing up memory space.
Definition at line 120 of file arraySorting.cpp.
{
    int *newSubArray = new int[rightIndex - leftIndex + 1];
    unsigned int startIndexPointer = leftIndex;
    unsigned int endIndexPointer = middleIndex + 1;
    unsigned int newIndexPointer = 0;
    while (startIndexPointer <= middleIndex && endIndexPointer <= rightIndex) {
        if (subArray[startIndexPointer] <= subArray[endIndexPointer]) {
            newSubArray[newIndexPointer] = subArray[startIndexPointer];
            startIndexPointer++;
        } else {
            newSubArray[newIndexPointer] = subArray[endIndexPointer];
            endIndexPointer++;
        }
        newIndexPointer++;
    }
    while (startIndexPointer <= middleIndex) {
        newSubArray[newIndexPointer] = subArray[startIndexPointer];
        startIndexPointer++;
        newIndexPointer++;
    }
    while (endIndexPointer <= rightIndex) {
        newSubArray[newIndexPointer] = subArray[endIndexPointer];
        endIndexPointer++;
        newIndexPointer++;
    }
    copyNewArrayIntoOriginalArray(newSubArray, subArray, rightIndex - leftIndex + 1, leftIndex);
    delete[] newSubArray;
}
References copyNewArrayIntoOriginalArray().
Referenced by mergeSortArray().
printArraySize()
void ArraySorting::printArraySize () const inline private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: inline Method to print array size.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - array size is printed to the console.
printing array size to the console. using endl to go to next line.
Definition at line 491 of file arraySorting.cpp.
{
    cout << endl << "For array size: " << SIZE_OF_2D_ARRAY << endl << endl;
}
References SIZE_OF_2D_ARRAY.
Referenced by display().
printDivider()
void ArraySorting::printDivider () inline private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: inline Method to print a divider line.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - a line is printed to the console.
printing - to the console. using endl to go to next line.
Definition at line 328 of file arraySorting.cpp.
{
    cout
            << "---------------------------------------------------------------------------------------------------------------------------------------------"
            << endl;
}
Referenced by display().
printDoubleDivider()
void ArraySorting::printDoubleDivider () inline private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: inline Method to print a divider line.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - a line is printed to the console.
printing = to the console. using endl to go to next line.
Definition at line 311 of file arraySorting.cpp.
{
    cout
            << "============================================================================================================================================="
            << endl;
}
Referenced by display().
printHeader()
void ArraySorting::printHeader () inline private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: inline Method to print a table header.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - a table header is printed to the console.
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using pipe '|' to separate columns.
this loops will run until i is equal to length of ArraySorting::NUMBER_OF_ARRAYS U as a suffix to 0 means only unsigned values
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using to_string() to convert a non string value to string such as int, float, double and char
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using pipe '|' to separate columns.
using endl to go to next line.
Definition at line 345 of file arraySorting.cpp.
{
    cout << left << setw(20) << "| Time Test";
    for (int i = 0U; i < NUMBER_OF_ARRAYS; i++) {
        cout << left << setw(12) << "| Array " + to_string(i + 1) + " ";
    }
    cout << left << setw(1) << "|" << endl;
}
References NUMBER_OF_ARRAYS.
Referenced by display().
printRandomTimeResult()
void ArraySorting::printRandomTimeResult () inline private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: inline Method to print execution time for random array sorting.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - values printed to the console.
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using pipe '|' to separate columns.
using range based for loop to iterate through the array ArraySorting::estimatedTimeForSortingRandomArr
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using setprecision = 6 to set the decimal values upto 5 digits.
using pipe '|' to separate columns.
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using pipe '|' to separate columns.
using endl to go to next line.
Definition at line 381 of file arraySorting.cpp.
{
    cout << left << setw(20) << "| Random Time (ms)";
    for (double i: estimatedTimeForSortingRandomArr) {
        cout << left << setw(2) << "| " << setw(10) << setprecision(6) << i;
    }
    cout << left << setw(1) << "|" << endl;
}
References estimatedTimeForSortingRandomArr.
Referenced by display().
printReverseTimeResult()
void ArraySorting::printReverseTimeResult () inline private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: inline Method to print execution time for reversed array sorting.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - values printed to the console.
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using pipe '|' to separate columns.
using range based for loop to iterate through the array ArraySorting::estimatedTimeForReversingSortedArr
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using setprecision = 6 to set the decimal values upto 5 digits.
using pipe '|' to separate columns.
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using pipe '|' to separate columns.
using endl to go to next line.
Definition at line 454 of file arraySorting.cpp.
{
    cout << left << setw(20) << "| Reverse Time (ms)";
    for (double i: estimatedTimeForReversingSortedArr) {
        cout << left << setw(2) << "| " << setw(10) << setprecision(6) << i;
    }
    cout << left << setw(1) << "|" << endl;
}
References estimatedTimeForReversingSortedArr.
Referenced by display().
printSortedTimeResult()
void ArraySorting::printSortedTimeResult () inline private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: inline Method to print execution time for sorted array sorting.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - values printed to the console.
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using pipe '|' to separate columns.
using range based for loop to iterate through the array ArraySorting::estimatedTimeForSortingSortedArr
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using setprecision = 6 to set the decimal values upto 5 digits.
using pipe '|' to separate columns.
using left keyword to left-align the data.
using setw to have a well-formatted output with spacing of the specified width.
using pipe '|' to separate columns.
using endl to go to next line.
Definition at line 417 of file arraySorting.cpp.
{
    cout << left << setw(20) << "| Sorted Time (ms)";
    for (double i: estimatedTimeForSortingSortedArr) {
        cout << left << setw(2) << "| " << setw(10) << setprecision(6) << i;
    }
    cout << left << setw(1) << "|" << endl;
}
References estimatedTimeForSortingSortedArr.
Referenced by display().
reverseSortedArray()
void ArraySorting::reverseSortedArray () private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: Method to reverse the an array.
Parameters
[in] void
Returns
[out] void
Postcondition
Post Condition - array is reversed
using 2 for loops to iterate through each array and swap the values to reverse the array.
U as a suffix to 0 means only unsigned values.
U as a suffix to 0 means only unsigned values
calling function ArraySorting::swap to swap values of 2 integers.
Definition at line 240 of file arraySorting.cpp.
{
    for (int i = 0U; i < NUMBER_OF_ARRAYS; i++) {
        for (int j = 0U; j < SIZE_OF_2D_ARRAY / 2; j++) {
            swap(array[i][j], array[i][SIZE_OF_2D_ARRAY - j - 1]);
        }
    }
}
References array, NUMBER_OF_ARRAYS, SIZE_OF_2D_ARRAY, and swap().
Referenced by ArraySorting().
sortArray()
void ArraySorting::sortArray (double timeArray[]) private
method taking no param
Module Name: Execution time for sorting random, sorted and reversed arrays.
Author: Faisal Javed
Date of Creation: 7th October, 2022
Purpose: Method to sort the array by calling merge sort algorithm and calculating the execution time for sorting the array.
Parameters
[in] timeArray
Returns
[out] void
Precondition
Pre Condition - an array is passed
Postcondition
Post Condition - execution time for each array is stored in an array
using for loop to iterate through each array and calculate the execution time.
U as a suffix to 0 means only unsigned values.
storing the time point representing the current time in startTime variable.
calling function ArraySorting::mergeSortArray to sort the array using merge sort.
storing the time point representing the current time in endTime variable.
calculating the elapsed time in millisecond from startTime and endTime.
Definition at line 213 of file arraySorting.cpp.
{
    for (int i = 0U; i < NUMBER_OF_ARRAYS; i++) {
        auto startTime = steady_clock::now();
        mergeSortArray(array[i], 0, SIZE_OF_2D_ARRAY - 1);
        auto endTime = steady_clock::now();
        timeArray[i] = duration_cast<microseconds>(endTime - startTime).count() / 1000.0;
    }
}
References array, mergeSortArray(), NUMBER_OF_ARRAYS, and SIZE_OF_2D_ARRAY.
Referenced by ArraySorting().
swap()
void ArraySorting::swap (int & firstValue, int & secondValue) private
method taking taking 2 params
Module Name: Execution time for sorting random, sorted and reversed arrays. Author: Faisal Javed Date of Creation: 7th October, 2022 Purpose: Method to swap the values.
Parameters
[in] void
Returns
[out] void
Precondition
Pre Condition - 2 int are passed.
Postcondition
Post Condition - values are swapped.
using a temporary variable to store the first value.
assigning the value of 2nd variable to first variable.
assigning the value of first variable stored in a temporary variable to the 2nd variable.
Definition at line 264 of file arraySorting.cpp.
{
    int temp = firstValue;
    firstValue = secondValue;
    secondValue = temp;
}
Referenced by reverseSortedArray().
Member Data Documentation
array
int** ArraySorting::array = new int * [NUMBER_OF_ARRAYS] private
2D int ** array. In a two dimensional array, we can access each element by using two subscripts, where first subscript represents the row number and second subscript represents the column number. int ** array point to a int * array which holds a pointer to an int value for each element.
Definition at line 72 of file arraySorting.h.
Referenced by createRandomIntArray(), reverseSortedArray(), and sortArray().
estimatedTimeForReversingSortedArr
double ArraySorting::estimatedTimeForReversingSortedArr[NUMBER_OF_ARRAYS] {} private
double array declared
Definition at line 65 of file arraySorting.h.
Referenced by ArraySorting(), and printReverseTimeResult().
estimatedTimeForSortingRandomArr
double ArraySorting::estimatedTimeForSortingRandomArr[NUMBER_OF_ARRAYS] {} private
double array declared
Definition at line 57 of file arraySorting.h.
Referenced by ArraySorting(), and printRandomTimeResult().
estimatedTimeForSortingSortedArr
double ArraySorting::estimatedTimeForSortingSortedArr[NUMBER_OF_ARRAYS] {} private
double array declared
Definition at line 61 of file arraySorting.h.
Referenced by ArraySorting(), and printSortedTimeResult().
NUMBER_OF_ARRAYS
const int ArraySorting::NUMBER_OF_ARRAYS = 10 static private
int variable assigned value 10.
Definition at line 49 of file arraySorting.h.
Referenced by createRandomIntArray(), printHeader(), reverseSortedArray(), and sortArray().
SIZE_OF_2D_ARRAY
unsigned int ArraySorting::SIZE_OF_2D_ARRAY private
unsigned int variable declared.
Definition at line 53 of file arraySorting.h.
Referenced by ArraySorting(), createRandomIntArray(), printArraySize(), reverseSortedArray(), and sortArray().
The documentation for this class was generated from the following files:
section1/arraySorting.h
section1/arraySorting.cpp