CS-700 Assignment 2: section2/sin_cos.cpp File Reference
sin_cos.cpp File Reference
#include <iostream>
#include <iomanip>
#include "sin_cos.h"
Functions
int sin (int x)
int cos (int x)
int sin0to45 (int x)
int sin45to90 (int x)
int polyEval (int x, int coef[], int n)
void testSineValues (int &passedValue, int expectedValue)
void testCosineValues (int &passedValue, int expectedValue)
void printDashedLine ()
void printTableHeader (string sineCosine)
void printResult (int &passedValue, int &valueOfSineCosine, int &expectedValue, string &result, string sineCosine)
Function Documentation
cos()
int cos (int x)
Compute the cosine of an angle in degrees.
Parameters
x The angle in degrees
Returns
The cosine of x
Definition at line 49 of file sin_cos.cpp.
               {
    return sin(x + 90);
}
References sin().
Referenced by testCosineValues().
polyEval()
int polyEval (int x, int coef[], int n)
Function to evaluate a polynomial
Parameters
x The point at which the polynomial is to be evaulated
coef The array of coefficients
n The number of coefficients (degree + 1)
Returns
x^n-1*coef[0] + x^n-2*coef[1] + ... x*coef[n-2] + coef[n-1]
Definition at line 87 of file sin_cos.cpp.
{
    int result = 0;
    for (int i = 0; i < n; i++) {
        result *= x;
        result += coef[i];
    }
    return result;
}
Referenced by sin0to45(), and sin45to90().
printDashedLine()
void printDashedLine () inline
Module Name: White box testing of sines and cosines. Author: Faisal Javed Date of Creation: 7th October, 2022 Purpose: function to print a line using '='
Parameters
void
Returns
void
Postcondition
Post Condition - a line is printed
printing '=' to the console. using endl to go to next line.
Definition at line 161 of file sin_cos.cpp.
{
    cout << "=============================================================" << endl;
}
Referenced by testCosineValues(), and testSineValues().
printResult()
void printResult (int & passedValue, int & valueOfSineCosine, int & expectedValue, string & result, string sineCosine) inline
Module Name: White box testing of sines and cosines. Author: Faisal Javed Date of Creation: 7th October, 2022 Purpose: function to print test case result of sine/cosine in a formatted fashion.
Parameters
passedValue
valueOfSineCosine
expectedValue
result
sineCosine
Returns
void
Postcondition
Post Condition - test case result is printed.
using left keyword to left-align the data. using setw to have a well-formatted output with spacing of the specified width. using pipe '|' to separate columns. using endl to go to next line.
Definition at line 201 of file sin_cos.cpp.
{
    cout << left << setw(17) << "| " + sineCosine + "(" + to_string(passedValue) + ")" << setw(17)
         << "| " + to_string(valueOfSineCosine) << setw(17) << "| " +
                                                               to_string(expectedValue) << setw(17)
         << "| " + result + "   |" << endl;
}
Referenced by testCosineValues(), and testSineValues().
printTableHeader()
void printTableHeader (string sineCosine) inline
Module Name: White box testing of sines and cosines. Author: Faisal Javed Date of Creation: 7th October, 2022 Purpose: function to print the table header
Parameters
sineCosine
Returns
void
Postcondition
Post Condition - a table header is printed
using left keyword to left-align the data. using setw to have a well-formatted output with spacing of the specified width. using pipe '|' to separate columns. using endl to go to next line.
Definition at line 176 of file sin_cos.cpp.
{
    cout << left << setw(17) << "| " + sineCosine + " Value " << setw(17) << "| Test Value " << setw(17)
         << "| Actual Value "
         << setw(17) << "| Result |" << endl;
}
Referenced by testCosineValues(), and testSineValues().
sin()
int sin (int x)
These functions compute the sine and cosine of an angle expressed in degrees. The result will be an integer representing the sine or cosine as ten-thousandths. For example, a result of 7071 represents 7071e-4 or 0.7071. Compute the sine of an angle in degrees.
Parameters
x The angle in degrees
Returns
The sine of x
Definition at line 29 of file sin_cos.cpp.
               {
    if (x < 0) {
        x = -x;
    }
    x = x % 360;
    if (0 <= x && x <= 45) {
        return sin0to45(x);
    } else if (45 <= x && x <= 90) {
        return sin45to90(x);
    } else if (90 <= x && x <= 180) {
        return sin(180 - x);
    } else {
        return -sin(x - 180);
    }
}
References sin(), sin0to45(), and sin45to90().
Referenced by cos(), sin(), and testSineValues().
sin0to45()
int sin0to45 (int x)
Compute the sine of an angle in degrees between 0 and 45. pre: 0 <= x < 45
Parameters
x The angle
Returns
The sine of x
Definition at line 59 of file sin_cos.cpp.
                    {
    // Code to compute sin(x) for x between 0 and 45 degrees
    // Evaluate a polynomial optimized for this range.
    int coef[] = {
            -81, -277, 1747900, -1600};
    return polyEval(x, coef, 4) / 10000;
}
References polyEval().
Referenced by sin().
sin45to90()
int sin45to90 (int x)
Compute the sine of an angle in degrees between 45 and 90. pre: 45 <= x <= 90
Parameters
x The angle
Returns
The sine of x
Definition at line 73 of file sin_cos.cpp.
                     {
    // Code to compute sin(x) for x between 45 and 90 degrees
    // Evaluate a polynomial optimized for this range.
    int coef[] = {
            336, -161420, 75484, 999960000};
    return polyEval(90 - x, coef, 4) / 100000;
}
References polyEval().
Referenced by sin().
testCosineValues()
void testCosineValues (int & passedValue, int expectedValue)
Module Name: White box testing of sines and cosines. Author: Faisal Javed Date of Creation: 7th October, 2022 Purpose: function white box test the values of cosines.
Parameters
passedValue
expectedValue
Returns
void
Precondition
Pre Condition - 2 int are passed.
Postcondition
Post Condition - result table is printed
storing the value of sin for the passed value in valueOfCosine
declaring a string result to store the result after white box testing
store the value PASS if the if condition is true
else store the value FAIL if the if condition is false
calling function printDashedLine() to print dashed line.
calling function printTableHeader() to print header for cosine.
calling function printDashedLine() to print dashed line.
calling function printResult() to print the result of whitebox testing.
calling function printDashedLine() to print dashed line.
using endl to go to next line.
Definition at line 135 of file sin_cos.cpp.
{
    int valueOfCosine = cos(passedValue);
    string result;
    if (valueOfCosine == expectedValue) {
        result = "PASS";
    } else {
        result = "FAIL";
    }
    printDashedLine();
    printTableHeader("Cosine");
    printDashedLine();
    printResult(passedValue, valueOfCosine, expectedValue, result, "Cosine");
    printDashedLine();
    cout << endl;
}
References cos(), printDashedLine(), printResult(), and printTableHeader().
testSineValues()
void testSineValues (int & passedValue, int expectedValue)
Module Name: White box testing of sines and cosines. Author: Faisal Javed Date of Creation: 7th October, 2022 Purpose: function white box test the values of sines.
Parameters
passedValue
expectedValue
Returns
void
Precondition
Pre Condition - 2 int are passed.
Postcondition
Post Condition - result table is printed
storing the value of sin for the passed value in valueOfSine
declaring a string result to store the result after white box testing
store the value PASS if the if condition is true
else store the value FAIL if the if condition is false
calling function printDashedLine() to print dashed line.
calling function printTableHeader() to print header for sine.
calling function printDashedLine() to print dashed line.
calling function printResult() to print the result of whitebox testing.
calling function printDashedLine() to print dashed line.
using endl to go to next line.
Definition at line 107 of file sin_cos.cpp.
{
    int valueOfSine = sin(passedValue);
    string result;
    if (valueOfSine == expectedValue) {
        result = "PASS";
    } else {
        result = "FAIL";
    }
    printDashedLine();
    printTableHeader("Sine");
    printDashedLine();
    printResult(passedValue, valueOfSine, expectedValue, result, "Sine");
    printDashedLine();
    cout << endl;
}
References printDashedLine(), printResult(), printTableHeader(), and sin().